### ISSUE TITLE
DLC vehicles are despawning in b3095

### ISSUE THREAD

**Issue by katsutosh** [itsjustcurtis/MenyooSP#7] opened 2024-01-21 14:27 UTC
after the change in commit https://github.com/itsjustcurtis/MenyooSP/commit/259aa9687013ef8e77536d362bfb5cdaef955978 dlc vehicles are despawning in b3095
before this commit it's works fine

**Comment by itsjustcurtis** [comment] 2024-01-21 17:28
This is really odd, the vehicles were despawning in SP until I made that change.

**Comment by itsjustcurtis** [comment] 2024-01-21 17:38
Duplicate of #6 - Re-opening for history and closing this

**Closed as completed by itsjustcurtis** 2024-01-21 17:38 UTC
Labels: bug, duplicate
