### ISSUE TITLE
Are there no Chop Shop decals?

### ISSUE THREAD

**Issue by ThatRealSpicyDragon** [itsjustcurtis/MenyooSP#79] opened 2024-03-25 22:07 UTC
![image_2024-03-25_220724634](https://github.com/itsjustcurtis/MenyooSP/assets/158034338/45bc974d-8b48-497f-9234-fdf08ced777d)

**Comment by itsjustcurtis** [comment] 2024-03-30 09:39
duplicate of #27

**Closed as not planned by itsjustcurtis** 2024-03-30 09:39 UTC
Labels: duplicate
